# docker-redis.yml - Standalone Redis service
# Usage: docker compose -f docker-redis.yml up -d

services:
  redis:
    image: redis:7-alpine
    container_name: lcm-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  redis-data:
