services:
  test:
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        BACKEND: cpu
        GIT_SHA: ${GIT_SHA:-dev}
    image: harbor.lan/dreamlab-test:latest
    container_name: dreamlab-test
    env_file:
      - env.dev
    environment:
      BACKEND: cpu
      MODE_CONFIG_PATH: /conf
    volumes:
      - ./server:/app/server:ro,Z
      - ./backends:/app/backends:ro,Z
      - ./utils:/app/utils:ro,Z
      - ./persistence:/app/persistence:ro,Z
      - ./tests:/app/tests:ro,Z
      - ./invokers:/app/invokers:ro,Z
      - ${TEST_MODELS_HOST_PATH:-./models}:/models:ro,Z
      - ${TEST_FS_HOST_PATH:-./store}:/store:rw,Z
      - ${TEST_WORKFLOW_HOST_PATH:-./workflows}:/workflows:rw,Z
      - ./conf/modes-test.yml:/conf/modes.yml:ro,Z
      - ./logs:/app/logs:rw,Z
      - ./htmlcov:/app/htmlcov:rw,Z
    command: pytest tests/ -v --cov=backends --cov=server --cov-report=html --cov-report=term-missing

  test-cuda:
    extends: test
    platform: linux/amd64
    container_name: dreamlab-test-cuda
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        BACKEND: cuda
        GIT_SHA: ${GIT_SHA:-dev}
    env_file:
      - env.dev
      - env.cuda
    environment:
      BACKEND: cuda
      MODE_CONFIG_PATH: /conf

  test-unit:
    extends: test
    container_name: dreamlab-test-not-ws
    command: pytest tests/ -v -m "not ws"

  test-ws:
    extends: test
    container_name: dreamlab-test-ws
    command: pytest tests/ -m ws -v

  test-fast:
    extends: test
    container_name: dreamlab-test-fast
    command: pytest tests/ -v -m "not slow"

  test-watch:
    extends: test
    container_name: dreamlab-test-watch
    command: ptw tests/ -- -v
